repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=120]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]

      - id: flake
        name: flake
        entry: flake8
        language: system
        types: [python]
